# Generated by Django 4.2.5 on 2023-09-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255, verbose_name='route')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('combined', models.CharField(max_length=255, verbose_name='combined')),
                ('distance', models.IntegerField(verbose_name='diatance')),
                ('departure', models.IntegerField(verbose_name='diatance')),
                ('bustroute', models.IntegerField(verbose_name='diatance')),
                ('arrivaltime', models.TimeField(verbose_name='arrivaltime')),
                ('bustime', models.TimeField()),
            ],
        ),
    ]
