# Generated by Django 4.2.5 on 2023-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_app1_departure_alter_app1_bustroute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app1',
            name='bustroute',
            field=models.CharField(max_length=255, verbose_name='busroute'),
        ),
    ]
